apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-aws-provider
  namespace: dev  \\ Has to match the namespace of the resource which is going to use the secret
spec:
  provider: aws  \\ Specify the provider as aws
  parameters:  \\ Specify provider-specific parameters
    objects: |
      - objectName: "MyTestSecret"  \\ This is the secret name you created in AWS
        objectType: "secretsmanager"
