apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secret-provider-app
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-cluster-csi-drivers
    server: https://kubernetes.default.svc
  project: default
  source:
    path: test-secret
    repoURL: https://github.com/varshab1210/gitops.git
  syncPolicy:
    automated:
    prune: true
    selfHeal: true
